name: music_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  
 
  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  responsive_framework: ^0.2.0
  google_fonts: ^4.0.3
  animated_notch_bottom_bar: ^0.0.6
  flick_video_player: ^0.5.0
  visibility_detector: ^0.4.0+2
  we_slide: ^2.4.0
  colorful_safe_area: ^1.0.0
  easy_scroll_animation: ^1.0.2
  delayed_widget: ^1.1.2
  lucide_icons: ^0.144.0
  audio_video_progress_bar: ^1.0.1
  rive: ^0.10.4
  marquee: ^2.2.3
  youtube_data_api:
    git:
      url: https://github.com/trunghq3101/YoutubeDataApi.git
  youtube_explode_dart: ^1.12.4
  just_audio: ^0.9.32
  get_storage: ^2.1.1
  shared_preferences: ^2.1.0
  animation_search_bar: ^0.0.10
  search_bar_animated: ^1.0.2
  shimmer: ^3.0.0
  flutter_vibrate: ^1.3.0
  genius_lyrics: ^0.0.9
 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/play_pause.riv
